# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp                    # ← デプロイ名（自由）
  labels:
    app: sampleapp
spec:
  replicas: 2                        # ← 必要に応じてスケール数
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      # AKS に ACR を attach 済みなら imagePullSecrets は不要
      # imagePullSecrets:
      #   - name: acr-pull-secret
      containers:
        - name: githubtestcontainer            # ← コンテナ名（自由だが一貫させる）          
          image: githubtestcontainer.azurecr.io/githubtestcontainer:0.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
